const GUIDES = {
  japan: { capitalKo: "도쿄", capitalEn: "Tokyo", ko: "엔화 지폐로 계산하고, 전철과 편의점은 교통카드로 내는 일이 많습니다.", en: "People pay with yen notes, and trains and convenience stores often take a transit card." },
  usa: { capitalKo: "워싱턴", capitalEn: "Washington", ko: "달러 지폐가 기준이고, 식당은 음식값과 팁이 따로인 곳이 많습니다.", en: "The dollar bill is the standard, and many restaurants keep the tip separate from the meal." },
  vietnam: { capitalKo: "하노이", capitalEn: "Hanoi", ko: "동은 액면 숫자가 커서, 지폐만 보고 비싸다고 느끼기 쉽습니다.", en: "The dong uses large face values, so a note can look expensive before you convert it." },
  thailand: { capitalKo: "방콕", capitalEn: "Bangkok", ko: "바트 동전과 지폐를 같이 쓰고, 시장 잔돈도 바트로 받습니다.", en: "Baht coins and notes are used together, and markets give change in baht." },
  taiwan: { capitalKo: "타이베이", capitalEn: "Taipei", ko: "신타이비로 편의점과 교통카드를 계산하는 일이 일상입니다.", en: "Convenience stores and transit cards are everyday ways to spend the New Taiwan dollar." },
  china: { capitalKo: "베이징", capitalEn: "Beijing", ko: "위안화를 쓰고, 도시에서는 모바일 결제가 현금보다 흔한 편입니다.", en: "Cities usually pay the yuan by phone more often than with cash." },
  philippines: { capitalKo: "마닐라", capitalEn: "Manila", ko: "페소로 지프니와 식사를 계산하고, 잔돈 동전이 중요합니다.", en: "Jeepneys and meals are priced in pesos, and coin change matters." },
  singapore: { capitalKo: "싱가포르", capitalEn: "Singapore", ko: "싱가포르 달러는 카드로 내는 일이 많고, 브루나이 달러와 1대 1로 통하는 곳도 있습니다.", en: "Cards are common, and the Brunei dollar is accepted 1 for 1 in many places." },
  hongkong: { capitalKo: "홍콩", capitalEn: "Hong Kong", ko: "홍콩 달러는 옥토퍼스 카드로 지하철과 편의점을 내는 경우가 많습니다.", en: "Many MTR rides and convenience stores take the Hong Kong dollar through an Octopus card." },
  macau: { capitalKo: "마카오", capitalEn: "Macau", ko: "파타카 가격표 옆에 홍콩 달러를 같이 받는 가게가 많습니다.", en: "Many shops list the pataca and also take Hong Kong dollars." },
  malaysia: { capitalKo: "쿠알라룸푸르", capitalEn: "Kuala Lumpur", ko: "링깃으로 나시 르막과 그랩 요금을 말합니다.", en: "Nasi lemak and Grab fares are quoted in ringgit." },
  indonesia: { capitalKo: "자카르타", capitalEn: "Jakarta", ko: "루피아는 자리 수가 커서, 음식과 택시 가격은 앞자리로 감을 잡는 편이 좋습니다.", en: "The rupiah has so many digits that meals and taxis are easier to judge by the first numbers." },
  australia: { capitalKo: "캔버라", capitalEn: "Canberra", ko: "호주 달러는 카드 결제가 기본에 가깝고, 커피 한 잔이 물가 감각의 기준이 됩니다.", en: "Card payment is close to the default, and a coffee is a common price benchmark." },
  guam: { capitalKo: "하갓냐", capitalEn: "Hagatna", ko: "미국 달러를 쓰므로 관광 식당과 렌터카도 미국과 같은 화폐로 계산합니다.", en: "Tourist meals and car rentals use the same US dollar as the mainland." },
  france: { capitalKo: "파리", capitalEn: "Paris", ko: "유로로 메트로와 카페를 계산하고, 카드 단말기가 거의 모든 가게에 있습니다.", en: "The metro and cafes are priced in euro, and card terminals are almost everywhere." },
  italy: { capitalKo: "로마", capitalEn: "Rome", ko: "같은 유로를 써도 에스프레소와 젤라또 가격 감각은 프랑스와 다릅니다.", en: "It uses the same euro, but espresso and gelato follow a different price habit than France." },
  spain: { capitalKo: "마드리드", capitalEn: "Madrid", ko: "유로로 하루 메뉴와 메트로 요금을 말합니다.", en: "Set lunches and the metro are quoted in euro." },
  germany: { capitalKo: "베를린", capitalEn: "Berlin", ko: "유로로 도너와 지역 교통표를 계산합니다.", en: "Doner and local transit tickets are priced in euro." },
  uk: { capitalKo: "런던", capitalEn: "London", ko: "파운드를 쓰고, 런던 대중교통은 접촉식 카드로 요금이 찍히는 구간이 많습니다.", en: "The pound is used, and much of London transit is charged by a contactless card." },
  switzerland: { capitalKo: "베른", capitalEn: "Bern", ko: "유로존이 아니라 프랑을 쓰며, 커피와 기차가 이웃 나라보다 비싸게 느껴집니다.", en: "It is outside the euro area and uses the franc, so coffee and trains feel expensive next to neighbors." },
  canada: { capitalKo: "오타와", capitalEn: "Ottawa", ko: "캐나다 달러로 커피와 지하철을 계산하며, 미국 달러와 액면이 다릅니다.", en: "Coffee and the subway are in Canadian dollars, which are not US dollars." },
  newzealand: { capitalKo: "웰링턴", capitalEn: "Wellington", ko: "뉴질랜드 달러는 쿡 제도와 니우에에서도 통하고, 본국 카페 가격이 기준이 됩니다.", en: "The New Zealand dollar also circulates in the Cook Islands and Niue, while home cafe prices set the reference." },
  turkey: { capitalKo: "앙카라", capitalEn: "Ankara", ko: "리라 표시 가격이 빨리 바뀌므로, 케밥과 차이 값은 그날 간판을 보는 편이 안전합니다.", en: "Lira price tags move quickly, so kebab and tea should be read from that day's sign." },
  uae: { capitalKo: "아부다비", capitalEn: "Abu Dhabi", ko: "디르함으로 메트로와 식사를 계산하고, 달러 현찰을 액면 그대로 받지 않는 곳이 많습니다.", en: "The metro and meals are in dirham, and many tills will not take US cash at face value." },
  laos: { capitalKo: "비엔티안", capitalEn: "Vientiane", ko: "공식 화폐는 킵이지만, 관광지에서는 바트나 달러가 섞이기도 합니다.", en: "The official money is the kip, though tourist spots sometimes mix in baht or dollars." },
  cambodia: { capitalKo: "프놈펜", capitalEn: "Phnom Penh", ko: "공식 화폐는 리엘이지만, 관광 계산은 미국 달러로 하는 곳이 많습니다.", en: "The official currency is the riel, but tourist bills are often in US dollars." },
  india: { capitalKo: "뉴델리", capitalEn: "New Delhi", ko: "루피로 차와 오토릭샤를 계산하고, 작은 지폐가 잘 통합니다.", en: "Tea and auto-rickshaws are priced in rupees, and small notes circulate easily." },
  mexico: { capitalKo: "멕시코시티", capitalEn: "Mexico City", ko: "페소로 타코와 지하철을 계산합니다.", en: "Tacos and the metro are priced in pesos." },
  czech: { capitalKo: "프라하", capitalEn: "Prague", ko: "유로존이 아니고, 맥주와 트램을 코루나로 계산합니다.", en: "It is outside the euro area and prices beer and trams in koruna." },
  korea: { capitalKo: "서울", capitalEn: "Seoul", ko: "원을 쓰고, 교통카드와 카드 결제가 현금보다 흔한 편입니다.", en: "The won is used, and transit cards and bank cards are more common than cash." },
  austria: { capitalKo: "빈", capitalEn: "Vienna", ko: "유로로 카페와 도시 교통을 계산합니다.", en: "Cafes and city transit are priced in euro." },
  belgium: { capitalKo: "브뤼셀", capitalEn: "Brussels", ko: "유로로 와플과 트램 요금을 말합니다.", en: "Waffles and trams are quoted in euro." },
  bulgaria: { capitalKo: "소피아", capitalEn: "Sofia", ko: "2026년부터 레프 대신 유로를 공식 화폐로 씁니다.", en: "The euro replaced the lev as official money in 2026." },
  croatia: { capitalKo: "자그레브", capitalEn: "Zagreb", ko: "쿠나를 접고 유로로 카페와 트램을 계산합니다.", en: "The kuna is gone, and cafes and trams are now in euro." },
  cyprus: { capitalKo: "니코시아", capitalEn: "Nicosia", ko: "유로존에서 커피와 버스를 유로로 냅니다.", en: "Coffee and buses are charged in euro." },
  estonia: { capitalKo: "탈린", capitalEn: "Tallinn", ko: "유로를 쓰고 카드 결제가 매우 흔한 편입니다.", en: "The euro is used, and card payment is very common." },
  finland: { capitalKo: "헬싱키", capitalEn: "Helsinki", ko: "유로로 커피와 교통을 내고, 현금을 거의 안 받는 가게도 있습니다.", en: "Coffee and transit are in euro, and some shops barely keep cash." },
  greece: { capitalKo: "아테네", capitalEn: "Athens", ko: "유로로 커피와 메트로를 계산합니다.", en: "Coffee and the metro are priced in euro." },
  ireland: { capitalKo: "더블린", capitalEn: "Dublin", ko: "유로로 펍과 버스 요금을 말합니다.", en: "Pubs and buses are quoted in euro." },
  latvia: { capitalKo: "리가", capitalEn: "Riga", ko: "유로로 카페와 트램을 계산합니다.", en: "Cafes and trams are priced in euro." },
  lithuania: { capitalKo: "빌뉴스", capitalEn: "Vilnius", ko: "유로를 쓰고, 도시에서는 카드가 잘 됩니다.", en: "The euro is used, and cards work well in cities." },
  luxembourg: { capitalKo: "룩셈부르크", capitalEn: "Luxembourg", ko: "유로를 쓰며, 버스가 무료인 구간이 있는지는 그 자리 안내를 보는 편이 좋습니다.", en: "The euro is used, and it is worth checking on the spot whether a bus ride is free." },
  malta: { capitalKo: "발레타", capitalEn: "Valletta", ko: "유로로 버스와 카페를 계산합니다.", en: "Buses and cafes are priced in euro." },
  netherlands: { capitalKo: "암스테르담", capitalEn: "Amsterdam", ko: "유로로 트램과 카페를 계산하고 카드 단말기가 흔합니다.", en: "Trams and cafes are in euro, and card terminals are common." },
  portugal: { capitalKo: "리스본", capitalEn: "Lisbon", ko: "유로로 커피와 메트로를 계산합니다.", en: "Coffee and the metro are priced in euro." },
  slovakia: { capitalKo: "브라티슬라바", capitalEn: "Bratislava", ko: "유로로 도시 교통과 점심을 계산합니다.", en: "City transit and lunch are priced in euro." },
  slovenia: { capitalKo: "류블랴나", capitalEn: "Ljubljana", ko: "유로를 쓰고, 작은 카페도 카드가 되는 곳이 많습니다.", en: "The euro is used, and even small cafes often take cards." },
  andorra: { capitalKo: "안도라라베야", capitalEn: "Andorra la Vella", ko: "자체 화폐 없이 유로를 공식 화폐로 씁니다.", en: "It has no currency of its own and uses the euro officially." },
  monaco: { capitalKo: "모나코", capitalEn: "Monaco", ko: "유로로 계산하므로 이웃 프랑스와 같은 화폐로 카페 가격을 비교하면 됩니다.", en: "Cafe prices compare directly with neighboring France because both use the euro." },
  sanmarino: { capitalKo: "산마리노", capitalEn: "San Marino", ko: "기념품 가게까지 유로로 계산합니다.", en: "Even souvenir shops charge in euro." },
  vatican: { capitalKo: "바티칸", capitalEn: "Vatican City", ko: "입장권과 기념품이 유로로 표시됩니다.", en: "Tickets and souvenirs are marked in euro." },
  kosovo: { capitalKo: "프리슈티나", capitalEn: "Pristina", ko: "유로존 회원은 아니지만 유로를 일상 화폐로 씁니다.", en: "It is not in the euro area, but the euro is the everyday money." },
  montenegro: { capitalKo: "포드고리차", capitalEn: "Podgorica", ko: "자체 화폐 없이 유로로 카페와 버스를 계산합니다.", en: "It has no currency of its own and prices cafes and buses in euro." },
  norway: { capitalKo: "오슬로", capitalEn: "Oslo", ko: "유로존이 아니고 크로네를 쓰며, 현금을 받지 않고 카드만 받는 가게가 많습니다.", en: "It is outside the euro area, uses the krone, and many shops take cards only." },
  sweden: { capitalKo: "스톡홀름", capitalEn: "Stockholm", ko: "크로나로 지하철을 내고, 현금을 거부하는 계산대가 많습니다.", en: "The subway is charged in kronor, and many tills refuse cash." },
  denmark: { capitalKo: "코펜하겐", capitalEn: "Copenhagen", ko: "크로네를 쓰고, 카드 결제가 현금보다 훨씬 흔합니다.", en: "The krone is used, and cards are much more common than cash." },
  iceland: { capitalKo: "레이캬비크", capitalEn: "Reykjavik", ko: "크로나로 거의 모든 것을 카드 결제하고, 식사 물가가 높게 느껴집니다.", en: "Almost everything is paid by card in krónur, and meals feel expensive." },
};
