const COUNTRIES = [
  {
    id: "japan",
    name: "일본",
    nameEn: "Japan",
    flag: "🇯🇵",
    code: "JPY",
    currencyEn: "Japanese Yen",
    currencyKo: "엔",
    unit: "엔",
    decimals: 0,
    amounts: [100, 500, 1000, 5000, 10000],
    defaultAmount: 1000,
    aliases: ["일본", "japan", "jpy", "엔", "yen", "니혼"],
    note: "",
    prices: [
      { name: "편의점 음료", amount: 160 },
      { name: "라멘", amount: 1000 },
      { name: "규동", amount: 500 },
      { name: "지하철 1회", amount: 180 },
      { name: "편의점 커피", amount: 150 },
    ],
  },
  {
    id: "usa",
    name: "미국",
    nameEn: "United States",
    flag: "🇺🇸",
    code: "USD",
    currencyEn: "US Dollar",
    currencyKo: "달러",
    unit: "달러",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["미국", "usa", "us", "america", "usd", "달러", "dollar", "불"],
    note: "가게에 따라 계산서 금액 외에 팁을 따로 내는 경우가 많아요.",
    prices: [
      { name: "커피", amount: 5 },
      { name: "지하철 1회", amount: 3 },
      { name: "햄버거", amount: 15 },
      { name: "점심 1인", amount: 22 },
      { name: "생수", amount: 2 },
    ],
  },
  {
    id: "vietnam",
    name: "베트남",
    nameEn: "Vietnam",
    flag: "🇻🇳",
    code: "VND",
    currencyEn: "Vietnamese Dong",
    currencyKo: "동",
    unit: "동",
    decimals: 0,
    amounts: [10000, 20000, 50000, 100000, 500000],
    defaultAmount: 100000,
    aliases: ["베트남", "vietnam", "vnd", "동", "dong"],
    note: "동은 단위가 커서 지폐 액면이 크게 보여도 원화로는 적은 금액인 경우가 많아요.",
    prices: [
      { name: "쌀국수", amount: 60000 },
      { name: "반미", amount: 30000 },
      { name: "커피", amount: 40000 },
      { name: "생맥주", amount: 20000 },
      { name: "단거리 그랩", amount: 35000 },
    ],
  },
  {
    id: "thailand",
    name: "태국",
    nameEn: "Thailand",
    flag: "🇹🇭",
    code: "THB",
    currencyEn: "Thai Baht",
    currencyKo: "바트",
    unit: "바트",
    decimals: 2,
    amounts: [20, 50, 100, 500, 1000],
    defaultAmount: 100,
    aliases: ["태국", "thailand", "thb", "바트", "baht"],
    note: "",
    prices: [
      { name: "생수", amount: 10 },
      { name: "음료", amount: 25 },
      { name: "길거리 식사", amount: 60 },
      { name: "BTS 1회", amount: 40 },
      { name: "마사지 1시간", amount: 300 },
    ],
  },
  {
    id: "taiwan",
    name: "대만",
    nameEn: "Taiwan",
    flag: "🇹🇼",
    code: "TWD",
    currencyEn: "New Taiwan Dollar",
    currencyKo: "대만 달러",
    unit: "달러",
    decimals: 0,
    amounts: [50, 100, 500, 1000, 5000],
    defaultAmount: 100,
    aliases: ["대만", "taiwan", "twd", "타이완", "신타이비"],
    note: "현지에서는 신타이비라고도 불러요. 여기서는 대만 달러로 표시합니다.",
    prices: [
      { name: "버블티", amount: 65 },
      { name: "우육면", amount: 180 },
      { name: "야시장 간식", amount: 50 },
      { name: "지하철 1회", amount: 30 },
      { name: "편의점 음료", amount: 35 },
    ],
  },
  {
    id: "china",
    name: "중국",
    nameEn: "China",
    flag: "🇨🇳",
    code: "CNY",
    currencyEn: "Chinese Yuan",
    currencyKo: "위안",
    unit: "위안",
    decimals: 2,
    amounts: [1, 10, 50, 100, 500],
    defaultAmount: 100,
    aliases: ["중국", "china", "cny", "위안", "yuan", "rmb", "인민폐"],
    note: "",
    prices: [
      { name: "지하철 1회", amount: 4 },
      { name: "만두", amount: 18 },
      { name: "커피", amount: 25 },
      { name: "식사 1인", amount: 40 },
      { name: "생수", amount: 3 },
    ],
  },
  {
    id: "philippines",
    name: "필리핀",
    nameEn: "Philippines",
    flag: "🇵🇭",
    code: "PHP",
    currencyEn: "Philippine Peso",
    currencyKo: "페소",
    unit: "페소",
    decimals: 2,
    amounts: [20, 50, 100, 500, 1000],
    defaultAmount: 100,
    aliases: ["필리핀", "philippines", "php", "페소", "peso"],
    note: "",
    prices: [
      { name: "지프니 단거리", amount: 15 },
      { name: "식사 1인", amount: 200 },
      { name: "맥주", amount: 60 },
      { name: "커피", amount: 120 },
      { name: "단거리 그랩", amount: 150 },
    ],
  },
  {
    id: "singapore",
    name: "싱가포르",
    nameEn: "Singapore",
    flag: "🇸🇬",
    code: "SGD",
    currencyEn: "Singapore Dollar",
    currencyKo: "싱가포르 달러",
    unit: "달러",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50],
    defaultAmount: 10,
    aliases: ["싱가포르", "singapore", "sgd", "싱달러"],
    note: "",
    prices: [
      { name: "호커 식사", amount: 8 },
      { name: "커피", amount: 5.5 },
      { name: "MRT 1회", amount: 2 },
      { name: "생수", amount: 1.5 },
      { name: "단거리 그랩", amount: 12 },
    ],
  },
  {
    id: "hongkong",
    name: "홍콩",
    nameEn: "Hong Kong",
    flag: "🇭🇰",
    code: "HKD",
    currencyEn: "Hong Kong Dollar",
    currencyKo: "홍콩 달러",
    unit: "달러",
    decimals: 2,
    amounts: [10, 20, 50, 100, 500],
    defaultAmount: 100,
    aliases: ["홍콩", "hongkong", "hong kong", "hk", "hkd"],
    note: "",
    prices: [
      { name: "우유차", amount: 25 },
      { name: "MTR 1회", amount: 8 },
      { name: "딤섬 점심", amount: 80 },
      { name: "편의점 음료", amount: 10 },
      { name: "계란 타르트", amount: 12 },
    ],
  },
  {
    id: "macau",
    name: "마카오",
    nameEn: "Macau",
    flag: "🇲🇴",
    code: "MOP",
    currencyEn: "Macanese Pataca",
    currencyKo: "파타카",
    unit: "파타카",
    decimals: 2,
    amounts: [10, 20, 50, 100, 500],
    defaultAmount: 100,
    aliases: ["마카오", "macau", "macao", "mop", "파타카", "pataca"],
    note: "홍콩 달러도 거의 같은 가치로 받는 곳이 많아요.",
    prices: [
      { name: "계란 타르트", amount: 12 },
      { name: "돼지빵", amount: 15 },
      { name: "버스 1회", amount: 6 },
      { name: "커피", amount: 30 },
      { name: "식사 1인", amount: 90 },
    ],
  },
  {
    id: "malaysia",
    name: "말레이시아",
    nameEn: "Malaysia",
    flag: "🇲🇾",
    code: "MYR",
    currencyEn: "Malaysian Ringgit",
    currencyKo: "링깃",
    unit: "링깃",
    decimals: 2,
    amounts: [1, 5, 10, 50, 100],
    defaultAmount: 10,
    aliases: ["말레이시아", "malaysia", "myr", "링깃", "ringgit"],
    note: "",
    prices: [
      { name: "나시 르막", amount: 12 },
      { name: "떼 타릭", amount: 3 },
      { name: "그랩 단거리", amount: 12 },
      { name: "MRT 1회", amount: 4 },
      { name: "커피", amount: 10 },
    ],
  },
  {
    id: "indonesia",
    name: "인도네시아",
    nameEn: "Indonesia",
    flag: "🇮🇩",
    code: "IDR",
    currencyEn: "Indonesian Rupiah",
    currencyKo: "루피아",
    unit: "루피아",
    decimals: 0,
    amounts: [10000, 20000, 50000, 100000, 500000],
    defaultAmount: 100000,
    aliases: ["인도네시아", "indonesia", "bali", "발리", "idr", "루피아", "rupiah"],
    note: "루피아도 단위가 큽니다. 액면 숫자만 보고 비싸다고 느끼지 않아도 돼요.",
    prices: [
      { name: "나시 고렝", amount: 35000 },
      { name: "커피", amount: 30000 },
      { name: "생맥주", amount: 40000 },
      { name: "단거리 그랩", amount: 25000 },
      { name: "마사지 1시간", amount: 150000 },
    ],
  },
  {
    id: "australia",
    name: "호주",
    nameEn: "Australia",
    flag: "🇦🇺",
    code: "AUD",
    currencyEn: "Australian Dollar",
    currencyKo: "호주 달러",
    unit: "달러",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["호주", "australia", "aud", "호주달러", "오스트레일리아"],
    note: "",
    prices: [
      { name: "커피", amount: 5.5 },
      { name: "점심 1인", amount: 20 },
      { name: "대중교통 단거리", amount: 4 },
      { name: "맥주", amount: 12 },
      { name: "생수", amount: 3 },
    ],
  },
  {
    id: "guam",
    name: "괌",
    nameEn: "Guam",
    flag: "🇬🇺",
    code: "USD",
    currencyEn: "US Dollar",
    currencyKo: "달러",
    unit: "달러",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 20,
    aliases: ["괌", "guam", "usd", "달러"],
    note: "괌에서 쓰는 돈은 미국 달러입니다.",
    prices: [
      { name: "커피", amount: 6 },
      { name: "햄버거", amount: 14 },
      { name: "편의점 물", amount: 2 },
      { name: "저녁 뷔페", amount: 40 },
      { name: "해변 주차", amount: 5 },
    ],
  },
  {
    id: "france",
    name: "프랑스",
    nameEn: "France",
    flag: "🇫🇷",
    code: "EUR",
    currencyEn: "Euro",
    currencyKo: "유로",
    unit: "유로",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["프랑스", "france", "eur", "유로", "euro", "유럽"],
    note: "프랑스는 유로를 씁니다. 이탈리아, 스페인, 독일과 같은 돈이에요.",
    prices: [
      { name: "에스프레소", amount: 2.5 },
      { name: "바게트", amount: 1.5 },
      { name: "메트로 1회", amount: 2.5 },
      { name: "점심 세트", amount: 16 },
      { name: "와인 한 잔", amount: 7 },
    ],
  },
  {
    id: "italy",
    name: "이탈리아",
    nameEn: "Italy",
    flag: "🇮🇹",
    code: "EUR",
    currencyEn: "Euro",
    currencyKo: "유로",
    unit: "유로",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["이탈리아", "italy", "eur", "유로", "euro", "유럽"],
    note: "이탈리아도 유로를 씁니다. 나라마다 물가는 달라요.",
    prices: [
      { name: "에스프레소", amount: 1.2 },
      { name: "젤라또", amount: 3 },
      { name: "피자", amount: 9 },
      { name: "시내 버스", amount: 1.5 },
      { name: "파스타", amount: 14 },
    ],
  },
  {
    id: "spain",
    name: "스페인",
    nameEn: "Spain",
    flag: "🇪🇸",
    code: "EUR",
    currencyEn: "Euro",
    currencyKo: "유로",
    unit: "유로",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["스페인", "spain", "eur", "유로", "euro", "유럽"],
    note: "스페인도 유로를 씁니다.",
    prices: [
      { name: "카페 콘 레체", amount: 2 },
      { name: "타파스", amount: 4 },
      { name: "메트로 1회", amount: 1.5 },
      { name: "하루 메뉴", amount: 15 },
      { name: "생맥주", amount: 3 },
    ],
  },
  {
    id: "germany",
    name: "독일",
    nameEn: "Germany",
    flag: "🇩🇪",
    code: "EUR",
    currencyEn: "Euro",
    currencyKo: "유로",
    unit: "유로",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["독일", "germany", "eur", "유로", "euro", "유럽"],
    note: "독일도 유로를 씁니다.",
    prices: [
      { name: "프레첼", amount: 2.5 },
      { name: "맥주 500ml", amount: 4.5 },
      { name: "지하철 단거리", amount: 3.5 },
      { name: "도너", amount: 7 },
      { name: "점심 1인", amount: 14 },
    ],
  },
  {
    id: "uk",
    name: "영국",
    nameEn: "United Kingdom",
    flag: "🇬🇧",
    code: "GBP",
    currencyEn: "British Pound",
    currencyKo: "파운드",
    unit: "파운드",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50],
    defaultAmount: 10,
    aliases: ["영국", "uk", "britain", "england", "gbp", "파운드", "pound"],
    note: "",
    prices: [
      { name: "커피", amount: 3.8 },
      { name: "지하철 1회", amount: 3 },
      { name: "피시 앤 칩스", amount: 12 },
      { name: "펍 식사", amount: 16 },
      { name: "생수", amount: 1.5 },
    ],
  },
  {
    id: "switzerland",
    name: "스위스",
    nameEn: "Switzerland",
    flag: "🇨🇭",
    code: "CHF",
    currencyEn: "Swiss Franc",
    currencyKo: "프랑",
    unit: "프랑",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["스위스", "switzerland", "chf", "프랑", "franc"],
    note: "스위스는 유로존이 아니라 프랑을 씁니다.",
    prices: [
      { name: "커피", amount: 5 },
      { name: "마트 생수", amount: 2 },
      { name: "기차 단거리", amount: 8 },
      { name: "점심 1인", amount: 25 },
      { name: "초콜릿", amount: 4 },
    ],
  },
  {
    id: "canada",
    name: "캐나다",
    nameEn: "Canada",
    flag: "🇨🇦",
    code: "CAD",
    currencyEn: "Canadian Dollar",
    currencyKo: "캐나다 달러",
    unit: "달러",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["캐나다", "canada", "cad", "캐나다달러"],
    note: "",
    prices: [
      { name: "커피", amount: 5 },
      { name: "점심 1인", amount: 18 },
      { name: "지하철 1회", amount: 3.5 },
      { name: "맥주", amount: 9 },
      { name: "생수", amount: 2 },
    ],
  },
  {
    id: "newzealand",
    name: "뉴질랜드",
    nameEn: "New Zealand",
    flag: "🇳🇿",
    code: "NZD",
    currencyEn: "New Zealand Dollar",
    currencyKo: "뉴질랜드 달러",
    unit: "달러",
    decimals: 2,
    amounts: [1, 5, 10, 20, 50, 100],
    defaultAmount: 10,
    aliases: ["뉴질랜드", "new zealand", "nzd", "뉴질랜드달러"],
    note: "",
    prices: [
      { name: "커피", amount: 5.5 },
      { name: "점심 1인", amount: 22 },
      { name: "버스 1회", amount: 4 },
      { name: "맥주", amount: 12 },
      { name: "파이", amount: 7 },
    ],
  },
  {
    id: "turkey",
    name: "튀르키예",
    nameEn: "Turkey",
    flag: "🇹🇷",
    code: "TRY",
    currencyEn: "Turkish Lira",
    currencyKo: "리라",
    unit: "리라",
    decimals: 2,
    amounts: [50, 100, 200, 500, 1000],
    defaultAmount: 200,
    aliases: ["튀르키예", "터키", "turkey", "turkiye", "try", "리라", "lira"],
    note: "리라는 물가 변화가 빨라서, 아래 가격은 여행 중 참고용으로만 보세요.",
    prices: [
      { name: "시밋", amount: 25 },
      { name: "차이", amount: 30 },
      { name: "케밥", amount: 350 },
      { name: "트램 1회", amount: 30 },
      { name: "커피", amount: 120 },
    ],
  },
  {
    id: "uae",
    name: "아랍에미리트",
    nameEn: "United Arab Emirates",
    flag: "🇦🇪",
    code: "AED",
    currencyEn: "UAE Dirham",
    currencyKo: "디르함",
    unit: "디르함",
    decimals: 2,
    amounts: [1, 5, 10, 50, 100],
    defaultAmount: 10,
    aliases: ["아랍에미리트", "uae", "dubai", "두바이", "aed", "디르함", "dirham"],
    note: "",
    prices: [
      { name: "메트로 1회", amount: 5 },
      { name: "커피", amount: 20 },
      { name: "식사 1인", amount: 45 },
      { name: "생수", amount: 2 },
      { name: "택시 기본", amount: 12 },
    ],
  },
  {
    id: "laos",
    name: "라오스",
    nameEn: "Laos",
    flag: "🇱🇦",
    code: "LAK",
    currencyEn: "Lao Kip",
    currencyKo: "킵",
    unit: "킵",
    decimals: 0,
    amounts: [10000, 20000, 50000, 100000, 500000],
    defaultAmount: 50000,
    aliases: ["라오스", "laos", "lak", "킵", "kip"],
    note: "관광지에서는 태국 바트나 미국 달러가 통하기도 해요. 공식 화폐는 킵입니다.",
    prices: [
      { name: "쌀국수", amount: 30000 },
      { name: "커피", amount: 20000 },
      { name: "맥주", amount: 15000 },
      { name: "툭툭 단거리", amount: 20000 },
      { name: "생수", amount: 5000 },
    ],
  },
  {
    id: "cambodia",
    name: "캄보디아",
    nameEn: "Cambodia",
    flag: "🇰🇭",
    code: "KHR",
    currencyEn: "Cambodian Riel",
    currencyKo: "리엘",
    unit: "리엘",
    decimals: 0,
    amounts: [1000, 5000, 10000, 20000, 50000],
    defaultAmount: 10000,
    aliases: ["캄보디아", "cambodia", "khr", "리엘", "riel"],
    note: "공식 화폐는 리엘이지만, 관광지에서는 미국 달러로 계산하는 곳이 많아요.",
    prices: [
      { name: "커피", amount: 6000 },
      { name: "식사 1인", amount: 20000 },
      { name: "맥주", amount: 4000 },
      { name: "툭툭 단거리", amount: 8000 },
      { name: "생수", amount: 1500 },
    ],
  },
  {
    id: "india",
    name: "인도",
    nameEn: "India",
    flag: "🇮🇳",
    code: "INR",
    currencyEn: "Indian Rupee",
    currencyKo: "루피",
    unit: "루피",
    decimals: 2,
    amounts: [10, 50, 100, 500, 1000],
    defaultAmount: 100,
    aliases: ["인도", "india", "inr", "루피", "rupee"],
    note: "",
    prices: [
      { name: "차", amount: 20 },
      { name: "탈리", amount: 250 },
      { name: "지하철 1회", amount: 30 },
      { name: "오토릭샤 단거리", amount: 80 },
      { name: "생수", amount: 20 },
    ],
  },
  {
    id: "mexico",
    name: "멕시코",
    nameEn: "Mexico",
    flag: "🇲🇽",
    code: "MXN",
    currencyEn: "Mexican Peso",
    currencyKo: "페소",
    unit: "페소",
    decimals: 2,
    amounts: [20, 50, 100, 200, 500],
    defaultAmount: 100,
    aliases: ["멕시코", "mexico", "mxn", "페소", "peso"],
    note: "",
    prices: [
      { name: "타코 3개", amount: 80 },
      { name: "지하철 1회", amount: 5 },
      { name: "맥주", amount: 50 },
      { name: "커피", amount: 60 },
      { name: "점심 1인", amount: 180 },
    ],
  },
  {
    id: "czech",
    name: "체코",
    nameEn: "Czech Republic",
    flag: "🇨🇿",
    code: "CZK",
    currencyEn: "Czech Koruna",
    currencyKo: "코루나",
    unit: "코루나",
    decimals: 2,
    amounts: [20, 50, 100, 500, 1000],
    defaultAmount: 100,
    aliases: ["체코", "czech", "czechia", "czk", "코루나", "koruna", "프라하"],
    note: "체코는 유로가 아니라 코루나를 씁니다.",
    prices: [
      { name: "맥주", amount: 60 },
      { name: "트램 1회", amount: 40 },
      { name: "점심 1인", amount: 180 },
      { name: "트르들로", amount: 80 },
      { name: "커피", amount: 70 },
    ],
  },
];
